### ISSUE TITLE
Is support for .NET Framework possible?

### ISSUE THREAD

**Issue by rafalkwol** [SteveSandersonMS/DotNetIsolator#4]
Hello,

I like the idea of this project. The thing that came to my mind right away when I seen the concept is a matter that I deal with very often in my work. I have to use legacy APIs to communicate with some external systems that are in form of .NET Framework assemblies. So far I usually solved it by running the .NET Framework API in a separate process and communicated via something like IPC etc. I would really love if it would be possible to get rid of separate processes and just run isolated .NET Framework assembly inside .NET Core process using this. Is this even possible or is it strictly for .NET Core code?

PS. Great work with this whole idea.

**Comment by iphdav** [comment]
.NET Framework for the most part requires Windows, so you are really asking if we can run Windows inside Web Assembly (so we can run .NET Framework code inside that virtualized Windows).  Nobody is going to realistically attempt this.

The closest you would get is a version of MONO running on one of the distributions of Linux that has been compiled to Web Assembly.  But I doubt that would solve your use case for legacy .NET Framework code - it would be hit and miss.

**Comment by SteveSandersonMS** [comment]
I agree with @iphdav - it's not something we'd attempt in this repo, and is unlikely to be viable due to the depth of .NET Framework's dependencies on Windows. Of course you're welcome to try to implement it yourself.

**Comment by rafalkwol** [comment]
Thanks for clarification. I think I will find use in the current version anyway, just wondered if it's possible to do this without much hassle, but it's clearly not a tivial thing from what I understand.
