### ISSUE TITLE
Question: DotNetWasmRunner Possibility 

### ISSUE THREAD

**Issue by Sharaf-Mansour** [SteveSandersonMS/DotNetIsolator#5]
Hey @SteveSandersonMS, You are a brilliant man and I admire all you work.
Science you did all your research around WASM and DotNet.

There is a common well known issue with dotnet published applications that I was trying to solve.

# The Issue
The published dotnet binaries are very easy to decompile using any free de-compiletion tools.
and it can be easily reveres engineered out of the box if there no protection was applied.
After watching your videos I got an idea.

# The Solution
Dotnet core EXE acts like a bootstrap that runs an external .DLL files containing your applications code.
Why not convert that code to a WASM file. (If Possible)  
For example publish as .WASM.
Then we build a generic simple DotNetWasmRunner. that run the .WASM file that contains your Dotnet code.
I am pretty sure if this was possible then it will apply a very simple and extra layer of protection to published binaries. 

# Help needed
I have no idea about its limitations or performance impact because I did not do much research in this area.
but I assume you might have an idea.
I got this idea when I first saw your WASI video but did not know when or where to ask you but after watching the DotNetIsolator videos I decided to just ask you here.

**Comment by omariom** [comment]
There will very soon be WASM decompiles.

Generally , nothing will protect you from reverse engineering.
Look at [Ghidra](https://ghidra-sre.org/) or [Ida-Pro](https://www.hex-rays.com/ida-pro/).
And with progress in AI it's getting even easier.

**Comment by SteveSandersonMS** [comment]
For clarification, this repo isn't involved in any compilation from .NET to WebAssembly, so is neither making your code easier nor harder to decompile. If you dig into how it works you'll see the WebAssembly files is just the runtime, not your application code. Your application code remains in regular .NET assemblies (`.dll` files) in your bin directory as usual.

Additionally I'd say that obfuscation is a losing battle and would recommend you don't try to rely on it either for security or for IP protection.
