### ISSUE TITLE
Is there any other place to ask general questions about the project or roadmap ?

### ISSUE THREAD

**Issue by coderookie1994** [SteveSandersonMS/DotNetIsolator#6]
It would be good if there was a discord channel or some other medium to reach out

**Comment by SteveSandersonMS** [comment]
Not really. GitHub issues are fine - feel free to post any general questions or discussions.

I'll close issues from time to time when the conversation seems to conclude.

**Comment by SteveSandersonMS** [comment]
Actually I've now just enabled https://github.com/SteveSandersonMS/DotNetIsolator/discussions

Thanks for the prompt!
